### ISSUE TITLE
DotNet cli build issue, After upgrading the fixie version to 3.0.0-beta.1

### ISSUE THREAD

**Issue by chan18** [fixie/fixie.benchmark#1]
.\build.cmd

dotnet --version

3.1.201

dotnet clean src -c $configuration --nologo -v minimal

dotnet build src -c $configuration --nologo

  Restore completed in 27.64 ms for H:\open-source\fixie.benchmark\src\Fixie.Tests\Fixie.Tests.csproj.
  Restore completed in 27.63 ms for H:\open-source\fixie.benchmark\src\CodeGeneration\CodeGeneration.csproj.
  Restore completed in 27.63 ms for H:\open-source\fixie.benchmark\src\Fixie.Tests\Fixie.Tests.csproj.
  Restore completed in 35.73 ms for H:\open-source\fixie.benchmark\src\xUnit.Tests\xUnit.Tests.csproj.
  CodeGeneration -> H:\open-source\fixie.benchmark\src\CodeGeneration\bin\Release\netcoreapp3.1\CodeGeneration.dll
  Fixie.Tests -> H:\open-source\fixie.benchmark\src\Fixie.Tests\bin\Release\netcoreapp3.1\Fixie.Tests.dll
  xUnit.Tests -> H:\open-source\fixie.benchmark\src\xUnit.Tests\bin\Release\netcoreapp3.1\xUnit.Tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.16

dotnet fixie --configuration $configuration --no-build

Fatal Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Fixie.Console.Program.RunTests(Options options, String testProject, String targetFramework, String[] customArguments, Boolean runningForMultipleFrameworks) in C:\dev\fixie\src\Fixie.Console\Program.cs:line 117
   at Fixie.Console.Program.Main(String[] arguments) in C:\dev\fixie\src\Fixie.Console\Program.cs:line 51

Expected return code 0, but was -1.

Build Failed

**Comment by chan18** [comment]
Invalid issue. 
Upgraded in the wrong way in the main branch. Closing it.
